### ISSUE TITLE
html being displayed in help menu of notebook

### ISSUE THREAD

**Issue by willingc** [jupyter/try.jupyter.org#11]
When a user opens a "Welcome to ..." notebook on the site and selects the Help menu, html is being displayed instead of the rendered content in the menu list. See example. I've filed here since I'm not sure if this is a tmpnb, tmpnb-deploy, notebook, or other issue as the root cause. FYI...it renders correctly in the dev version of the notebook running locally.
cc/ @Carreau @rgbkrk @minrk @takluyver

![screen shot 2016-04-28 at 10 23 03 am](https://cloud.githubusercontent.com/assets/2680980/14895153/14d16a34-0d2c-11e6-86cb-5f5d6d22abcc.png)

**Comment by willingc** [comment]
Okay, weird now it's working correctly. I tried it before in a regular Chrome window and an Incognito window and it was displaying as above. Hmmph... probably due to some weird caching. I :heart: computers. Sorry, I'm closing this.

**Comment by rgbkrk** [comment]
If I had to guess we have an old image configured for one of the tmpnb nodes that are in rotation. It's probably still there, hiding away.

**Comment by willingc** [comment]
@rgbkrk Fabulous 😑  Reopening...

**Comment by Carreau** [comment]
yeah, we should have fixed that bug a long time ago....

**Comment by minrk** [comment]
@Carreau fixed this in jupyter/notebook#401, which was part of notebook-4.1, but the tmpnb images are still using 4.0.5. We need to update the images on tmpnb.

**Comment by willingc** [comment]
@minrk @Carreau Thanks that would explain it. I'm going to close this here as the update is being done tracked in Operations.

**Comment by minrk** [comment]
I deployed some new instances with notebook-4.1, which fixes this.
