### ISSUE TITLE
Add sympy to the default image

### ISSUE THREAD

**Issue by fperez** [jupyter/try.jupyter.org#13]
As mentioned in [the help repo](https://github.com/jupyter/help/issues/60), the default image for try.jupyter doesn't ship Sympy. I think it's reasonable to add it to the base image for the future, sympy is an easy install, though I don't think it's high priority.

Pinging @fiziko, the OP for that request, in case you'd like to contribute a PR to add this feature.

**Comment by ghost** [comment]
Thanks, fperez, for entering this request here for me.

However, in contrast to you I do think, that adding SymPy should be high priority. It's true, that both Python 2 and 3 ship with large standard libraries. But for science and education: SymPy is "high-value".

Also, I do not see, why libs such as matplotlib, numpy and pandas are included - and sympy is not.

**Comment by fperez** [comment]
I didn't mean to imply that sympy isn't high value, just that try.jupyter is simply a demo that we offer to highlight the basics of Jupyter, it's not a comprehensive development environment with all the relevant libraries from the pydata ecosystem.

So while sympy is very important, we have a lot of things on our plate, and try.jupyter as it currently stands already fulfills its _demo_ mission. But next time we have a chance to work on it, adding sympy shouldn't be particularly hard, we just need to update the base docker image with the sympy install.

What I meant is: making _any_ updates to those images is right now fairly low priority, given that they work as a basic demo already and we don't host them for "real work".

I hope that's clear.

ps - I should probably have filed this issue [here instead](https://github.com/jupyter/docker-demo-images), which is where the docker images live.

**Comment by ghost** [comment]
thanks, It's clear. I fully understand... I also understand, that the demo-mission is already fulfilled. I am not saying, that jupyter itself needs SymPy necessarily. What I am trying to say is, that it would be very nice to also have SymPy in your try.jupyter.org demo... :-) 

I'd appreciate it, if you could file this "nice-to-have-request" at docker-demo-images, if that makes sense...

**Comment by minrk** [comment]
SymPy should be added to the image on the next build. It was on the image until recently, when we changed a bit how try.jupyter inherits from our docker stacks. Now, the image that installs sympy is back in the inheritance chain, so we will have it on next deploy.

**Comment by fperez** [comment]
Thanks @minrk! BTW, where is the Dockerfile for that base `all-spark-notebook` image? I couldn't find it... It would be good to list where it is on the README, I actually looked for it but I guess I don't know enough about the whole flow and couldn't find it (I found the image on dockerhub, but not the dockerfile).

**Comment by minrk** [comment]
Our for-inheriting docker images are built from [docker-stacks](https://github.com/jupyter/docker-stacks). This repo cleaned up and took over most of what was originally in docker-demo-images as proper base images for people to use. The demo repo now only builds the demo image for try.jupyter.org. I've added a link to the readme in #14
