### ISSUE TITLE
try.jupyter.org should redirect to HTTPS if loaded on HTTP

### ISSUE THREAD

**Issue by rgbkrk** [jupyter/try.jupyter.org#15]
If loaded over HTTP, the iframe for tmpnb will not load because it violates the content security policy:

<img width="1436" alt="screen shot 2016-07-26 at 3 12 25 pm" src="https://cloud.githubusercontent.com/assets/836375/17157333/7d31afaa-5343-11e6-8c39-4734fd8af04a.png">

**Comment by Carreau** [comment]
@fperez this is already an opened issue.

**Comment by fperez** [comment]
Thanks, @Carreau! @rgbkrk, is this an easy fix? I'm not up to speed on how tmpnb/tryjupyter is deployed, but right now this failure mode is going to make it look fully broken to a lot of users who simply try the naive thing of hitting try.jupyter.org without further qualification...

**Comment by rgbkrk** [comment]
The notebook server containers needed to be changed to have a more open content security policy in  docker-demo-images. It looks like this was already changed, and the build went out. Perhaps it was an old node still in rotation or something changed with the machine I'm on being on the latest Chrome and ~~OS X~~ macOS release - it now works flawlessly for me.

**Comment by alanhdu** [comment]
Hi!

I'm noticing this problem with Firefox (51a2 developer edition) on Ubuntu 16.04.

https://try.jupyter.org works fine, but when I go to http://try.jupyter.org, I get a big:
![image](https://cloud.githubusercontent.com/assets/1914111/20392985/11945b7e-acd2-11e6-8881-5475866cfb96.png)

This might be a Firefox-only problem -- Chrome redirects from http to https without any problems.

**Comment by alanhdu** [comment]
Hi again! Sorry to bug you about this, but I wanted to check whether there was any updates here. I'm going to be hosting a bunch of workshops in the next couple of weeks, and it'd be great to get this resolved.

It's not super urgent because the http -> https redirection is working perfectly for http://tmpnb.org (maybe the only thing to do here is to update / redeploy http://try.jupyter.org?), but it is a bit of a papercut.

**Comment by minrk** [comment]
@alanhdu sorry for the delay. It should be fixed now by [this](https://github.com/jupyter/try.jupyter.org/commit/2e812bb47eb3fd900a9612d97afb234ce04fa579).
