### ISSUE TITLE
"No Vacancy" at try.jupyter.org

### ISSUE THREAD

**Issue by JamiesHQ** [jupyter/try.jupyter.org#16]
A colleague of mine has been trying to check out Jupyter through try.jupyter.org and continues to get the No Vacancy message. Any idea when it will be freed up? Thanks!

**Comment by Carreau** [comment]
Seen to work for me now.

You can look at `https://tmpnb.org/stats` to look at statistics. 
Right now I have 81 container available.

```
{"available": 81, "hosts": {"https://tmp54.tmpnb.org": {"available": 26, "container_image": "jupyter/demo:latest", "version": "0.1.0", "capacity": 64}, "https://tmp55.tmpnb.org": {"available": 55, "container_image": "jupyter/demo:latest", "version": "0.1.0", "capacity": 64}}, "version": "0.0.1", "capacity": 128}
```

Can he access it if he hits `https://tmpnb.org` directly ?

**Comment by willingc** [comment]
Working today for me using `try.jupyter.org`. It wasn't working yesterday though. Perhaps a capacity issue since PyData Carolinas was going on. Going to close. Feel free to reopen if you see the behavior again.

**Comment by JamiesHQ** [comment]
Thanks @Carreau & @willingc
