### ISSUE TITLE
Add Rackspace logo

### ISSUE THREAD

**Issue by fperez** [jupyter/try.jupyter.org#6]
@rgbkrk, is this the right place for this one? I'd like to more publicly acknowledge Rackspace's contribution to try.jupyter by having a visible logo, much like it was done for the Nature demo.

If in the future, we have a more 'federated' model with other providers also hosting official try.jupyter instances, we can figure out how to properly acknowledge them all as well, obviously.  But might as well start by doing the n=1 case right :)

**Comment by fperez** [comment]
If this should go into another repo, let me know and we'll move it over. We can then ping everyone for comments once it's in the right place.

**Comment by minrk** [comment]
try.jupyter only contains an iframe that wraps tmpnb. The pages that people actually see are all served by the docker container we use for the demo, which are in [jupyter/docker-demo-images](https://github.com/jupyter/docker-demo-images).

**Comment by fperez** [comment]
Thanks @minrk, closing here and opening there.  I don't have the time obviously to do it, I just think we should :) We can discuss it there.

**Comment by rgbkrk** [comment]
Awesome, thank you. I've been hoping that we skin it too as well as provide an advisory about the temporaryness of their session. Perhaps a custom template across all the pages? We already inject Google Analytics on all the pages.

**Comment by fperez** [comment]
Kyle, note this issue has been closed, and discussion moved over to [#24 on docker-demo](https://github.com/jupyter/docker-demo-images/issues/24). I'll put your comment over there so we can continue.
